# Generated by Django 5.1.6 on 2025-02-25 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 9, 8, 2, 385926)),
        ),
    ]
